### ISSUE TITLE
Hvae you ever face this problem while training?

### ISSUE THREAD

**Issue by LT1st** [fangyuanmao/PID#12]
```
Global seed set to 23
Running on GPUs 2,3
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 241.49 M params.
Keeping EMAs of 278.
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
/root/miniforge3/envs/pid/lib/python3.8/site-packages/clip/clip.py:24: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
Spatial Rescaler mapping from 3 to 3 channels after resizing.
Restored from ./pretrained/TeVNet_FLIR/epoch_1000.pth with 0 missing and 0 unexpected keys
Successfully load
Monitoring val/loss_simple_ema as checkpoint metric.
Merged modelckpt-cfg: 
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/2024-11-11T23-02-18_cats512-vqf8/checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 3}}
Caution: Saving checkpoints every n train steps without deleting. This might require some free space.
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
Traceback (most recent call last):
  File "/home/LT/diffusion/PID/main.py", line 720, in <module>
    trainer.fit(model, data)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 462, in fit
    self.train_loop.setup_fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 117, in setup_fit
    self.trainer.data_connector.attach_data(model, train_dataloader, val_dataloaders, datamodule)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 84, in attach_data
    self.attach_datamodule(model, datamodule, 'fit')
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 127, in attach_datamodule
    if is_overridden('val_dataloader', datamodule):
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/utilities/model_helpers.py", line 42, in is_overridden
    is_overridden = instance_attr.__code__ is not super_attr.__code__
AttributeError: 'functools.partial' object has no attribute '__code__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/LT/diffusion/PID/main.py", line 722, in <module>
    melk()
  File "/home/LT/diffusion/PID/main.py", line 703, in melk
    trainer.save_checkpoint(ckpt_path)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/properties.py", line 327, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 401, in save_checkpoint
    checkpoint = self.dump_checkpoint(weights_only)
  File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 312, in dump_checkpoint
    checkpoint['state_dict'] = model.state_dict()
AttributeError: 'NoneType' object has no attribute 'state_dict'
#### Data #####
train, FLIRTrain, 586
validation, FLIRVal, 100
accumulate_grad_batches = 1
Setting learning rate to 4.00e-06 = 1 (accumulate_grad_batches) * 2 (num_gpus) * 2 (batchsize) * 1.00e-06 (base_lr)
Summoning checkpoint.

Process finished with exit code 1
```

**Comment by fangyuanmao** [comment]
Sorry, I have not encounter such problems. From `File "/root/miniforge3/envs/pid/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 312, in dump_checkpoint
    checkpoint['state_dict'] = model.state_dict()
AttributeError: 'NoneType' object has no attribute 'state_dict'`, it seems that the model is not well set.

**Comment by LT1st** [comment]
Thanks for your suggestions. I tried to downgrade my transformers lib, and it works!
